version: '3.7'
services:
  laravel-web:
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-web
    restart: unless-stopped
    tty: true
    env_file:
      - .env.laravel
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    # working_dir: /var/www/html/laravel-app
    volumes:
      - ./app:/var/www/html/laravel-app
    networks:
      - laravel-net

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    env_file:
      - .env.db
    volumes:
      - db:/var/lib/mysql/
    networks:
      - laravel-net

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html/laravel-app
      - ./conf/laravel.conf:/etc/nginx/conf.d/laravel.conf
    networks:
      - laravel-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html/laravel-app
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email laravel@example.com --agree-tos --no-eff-email --staging -d example.com
    # command: certonly --webroot --webroot-path=/var/www/html --email laravel@example.com --agree-tos --no-eff-email --force-renewal -d example.com

networks:
  laravel-net:
    driver: bridge

volumes:
  app:
  db:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
