FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nginx \
    supervisor

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

USER $user

# Set working directory
WORKDIR /var/www/html/

RUN composer create-project --prefer-dist laravel/laravel laravel-app

USER root

# Use supervisord instead of direct run for Nginx and PHP
COPY ./conf/supervisord.conf /etc/supervisord.conf

# PHP-FPM basic config file
COPY ./conf/fpm.conf /usr/local/etc/php-fpm.d/www.conf

# Adding startup script for Nginx and PHP
COPY /entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Exposing ports
EXPOSE 80 443 9000

CMD ["/entrypoint.sh"]

# ENTRYPOINT [""nginx", "-g", "daemon off;"]
#CMD ["php-fpm"]
